Feat: clear all button in null search results notification
ipfs/ecosystem-directory pull request #198
Opened 2021-07-23 15:53 UTC by svvimming

Clear all button added to the null search results prompt in project view.

2021-07-23 16:58 UTC, timelytree requested changes
Just some minor updates:
1. Let's squeeze into this PR → _all_ clear all buttons should also clear the FilterBar search input
2. From here on out _everything_ has to have interactions (hover effects) that matches the rest of the site. So in this case, the new Clear All button should highlight to `$ming` (`#34797D`) onhover

2021-07-23 16:58 UTC, timelytree commented on components/ProjectView/ProjectView.vue
> +  }
Just 2 reminders :)

- `@include borderRadius2;` should go at the top of the SCSS block
- We shouldn't use partial pixel values → `0.3 * 16px = 4.8px`. The browser rounds up to `5px` but we shouldn't make it have to do that 😬 in this case to convert `5px` to rems we'd do → `5 / 16 = 0.3125rem`. I know it's kind of awkward to work with `1px = 0.625rem` but you get used to it I promise!

2021-07-23 16:59 UTC, timelytree commented on components/ProjectView/ProjectView.vue
> +  }
And also mooooost of the time we use nicer-looking/feeling since or quarter-rems thankfully (re: `1rem, 3.25rem, 2.5rem`, etc)

2021-07-23 20:11 UTC, svvimming commented
All clear all buttons (additionally the one at the bottom of the filter panel) now clear the filter bar input. 
All other changes mentioned in the comments above have been implemented too!

2021-07-26 21:38 UTC, timelytree approved these changes

2021-07-26 21:38 UTC, merged